volumes:
  jenkins_data:


services:
  jenkins:
    image: swh-jenkins:latest
    build: ./docker
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker:/usr/libexec/docker
      - .:/opt/swh-jenkins-jobs
      - ./docker:/docker
      - ./docker/jenkins_jobs.ini:/etc/jenkins_jobs/jenkins_jobs.ini
    environment:
      - PLUGINS_FORCE_UPGRADE=true
      - >
        JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
          -Djenkins.install.runSetupWizard=false
          -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true
          -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
    ports:
      - 8080:8080
      # For docker agent
      - 50000:50000
    entrypoint: /docker/entrypoint.sh
