- job-group:
    name: swh-environment-jobs-{name}
    jobs:
      - "{name}"
      - "{name}/tests"
      - "{name}/docker-tests"

- job-template:
    name: "{name}/tests"
    display-name: tests
    gitlab_project_name: swh/devel/swh-environment
    description: Run tests for each swh module in development version
    project-type: pipeline
    docker_image: tox
    docker_options: --tmpfs /tmp:exec --privileged --device /dev/fuse
    python_version: "3.11"
    sandbox: true
    timeout: 120
    max_concurrent: 2

    triggers: !j2-yaml: |
      {% if production_jenkins %}
      - timed: "H */6 * * *"
      {% else %}
      []
      {% endif %}

    dsl: !include-jinja2: templates/swh-environment.groovy.j2

- job-template:
    name: "{name}/docker-tests"
    gitlab_project_name: swh/devel/docker
    gitlab_trigger: true
    description: >
      Build the swh/stack:latest image and run tests.

      Note that when triggered by gitlab, this will run the docker image build
      step WITHOUT the '--no-cache' option. So if you need to enforce
      rebuilding the image from scratch, trigger the job by hand from jenkins
      (or wait for the daily build to run).

    project-type: pipeline
    docker_image: tox
    docker_options: -v /tmp:/tmp
    sandbox: true
    max_concurrent: 2
    properties:
      - build-discarder:
          days-to-keep: 20
      - gitlab:
          connection: "{gitlab_connection_name}"
    triggers: !j2-yaml: |
      {% if production_jenkins %}
      - timed: "@midnight"
      {% endif %}
      - gitlab:
          trigger-push: true
          trigger-merge-request: true
          trigger-open-merge-request-push: source
          trigger-note: true
          note-regex: "@jenkins.*retry.*build"
          wip-skip: false
          add-ci-message: true
          cancel-pending-builds-on-update: true
          # secret jenkins token is generated when executing tox
          secret-token: !include-raw-verbatim: templates/jenkins-token

    dsl: !include-jinja2: templates/swh-docker-dev.groovy.j2

- project:
    name: DENV
    display-name: swh-environment
    jobs:
      - "swh-environment-jobs-{name}"
